version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    working_dir: /app
    command: bash
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER_MEMORY_LIMIT=-1
